# Generated by Django 5.1.5 on 2025-01-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('un_no', models.CharField(blank=True, max_length=20, null=True)),
                ('imco_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cas_no', models.CharField(blank=True, max_length=20, null=True)),
                ('msds', models.FileField(blank=True, null=True, upload_to='msds/')),
                ('coa', models.FileField(blank=True, null=True, upload_to='coa/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
