# Generated by Django 5.1.5 on 2025-01-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='cas_no',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='coa',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='imco_code',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='msds',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='un_no',
        ),
        migrations.AddField(
            model_name='chemical',
            name='cas_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='hs_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='uses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='chemicals.chemicalgroup'),
        ),
    ]
