# Generated by Django 5.1.5 on 2025-07-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_chemicalgroup_remove_chemical_cas_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chemicalgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
