# Generated by Django 5.1.5 on 2025-07-09 03:48

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    ChemicalGroup = apps.get_model('chemicals', 'ChemicalGroup')
    Chemical = apps.get_model('chemicals', 'Chemical')
    
    # Populate ChemicalGroup slugs
    for group in ChemicalGroup.objects.all():
        if not group.slug:
            group.slug = slugify(group.name)
            group.save()
    
    # Populate Chemical slugs
    for chemical in Chemical.objects.all():
        if not chemical.slug:
            chemical.slug = slugify(chemical.name)
            chemical.save()


def reverse_populate_slugs(apps, schema_editor):
    ChemicalGroup = apps.get_model('chemicals', 'ChemicalGroup')
    Chemical = apps.get_model('chemicals', 'Chemical')
    
    # Clear slugs (not really necessary for reverse, but for completeness)
    ChemicalGroup.objects.update(slug='')
    Chemical.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_chemical_slug_chemicalgroup_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
