# Generated by Django 5.1.5 on 2025-07-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0004_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='chemicalgroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
